Repository CommunityToolkit/Tooling-Windows-Submodule, pull requests merged in 2023-07, with the labels that each got.

#92 Bumped Uno to latest version
  MultiTarget/PackageReferences/Uno.props
  ProjectHeads/App.Head.props
Labels: dev loop ➰, Uno, low difficulty

#98 Fix issue where Rename-Item would fail when generating solution with PowerShell script
  ProjectHeads/GenerateSingleSampleHeads.ps1
Labels: bug :bug:, enhancement, templating

#97 Fixed sample projects always inheriting source project MultiTarget.props
  MultiTarget/GenerateAllProjectReferences.ps1
  MultiTarget/GenerateMultiTargetAwareProjectReferenceProps.ps1
  MultiTarget/GetMultiTargets.ps1
Labels: bug :bug:, dev loop ➰

#99 Setup Converters Package properly for Sample App Usage
  MultiTarget/UseUnoWinUI.ps1
  ProjectHeads/App.Head.Uno.UI.Dependencies.props
  ProjectHeads/App.Head.Uno.WinUI.Dependencies.props
  ProjectHeads/App.Head.Uno.props
  ProjectHeads/App.Head.Uwp.Dependencies.props
  ProjectHeads/App.Head.Uwp.props
  ProjectHeads/App.Head.WinAppSdk.Dependencies.props
  ProjectHeads/App.Head.WinAppSdk.props
  ProjectHeads/App.Head.props
Labels: bug :bug:, dev loop ➰, sample app 🖼, templating

#109 Fixed and updated UseTargetFrameworks script to accommodate submodule
  MultiTarget/UseTargetFrameworks.ps1
Labels: bug :bug:, dev loop ➰

#111 Fixed an issue building sample projects on macOS
  ToolkitComponent.SampleProject.props
Labels: bug :bug:, CI/pipeline 🔬, dev loop ➰, regression, Uno

#112 Fixed build errors when building Wasm with WinUI 3
  CommunityToolkit.App.Shared/App.xaml.cs
  CommunityToolkit.App.Shared/Controls/TitleBar/NativeMethods.cs
  CommunityToolkit.App.Shared/Controls/TitleBar/TitleBar.WASDK.cs
  CommunityToolkit.App.Shared/Controls/TitleBar/TitleBar.cs
Labels: bug :bug:, build :fire:, CI/pipeline 🔬, dev loop ➰, regression

#113 Suppress CA1060
  CommunityToolkit.App.Shared/Controls/TitleBar/NativeMethods.cs
Labels: bug :bug:, build :fire:, CI/pipeline 🔬, regression
